language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - nightly
  - hhvm
env:
  TRANSPILE=true
matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
  exclude:
    - php: hhvm
      env: TRANSPILE=false

install: composer install
before_script: $TRANSPILE && ./transpile && cd php
