#!/usr/bin/env bash

set -ev
if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then
    rm -rf ./php/
    h2tp ./src ./php/src
    h2tp ./test ./php/test
    cp -r /usr/share/hhvm/hack/hacklib ./php/
    cp -r ./vendor ./php/
    cp ./hack_test_bootstrap.php ./php/test/bootstrap.php
    cp ./phpunit.xml ./php/
else
    true
fi
